a = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços? ', a.isspace())
print('É numérico? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('Está em maiúsculo? ', a.isupper())
print('Está em minúsculo? ', a.islower())
